### ISSUE TITLE
EmberPusher doesn't need to be a controller

### ISSUE THREAD

**Issue by mmun** [jamiebikies/ember-pusher#6]
Now that we are injecting the pusher "service" into routes and controllers, we don't require the machinery of a Ember.Controller and should just extend Ember.Object.

**Comment by elskwid** [comment]
@mmun I was just thinking about this as we start to wire up pusher in our app. Could we just use `Ember.Service` and make it explicit?

**Comment by mmun** [comment]
@elskwid Yeah that's the plan - and move (un)subscriptions into routes so that they are scoped to whether you are in the route or not.

**Comment by jamiebikies** [comment]
I actually had things using routes very early on but I ended up moving to controllers. The problem is that sometimes it's nice that it stays bound and other times it's not. I suppose there could be a good argument made that you should just place the binding up higher in the route hierarchy if you want an event to be bound throughout the application.

**Comment by mmun** [comment]
It's totally fine to use services in that case.
